//! Derive `packages/protocol/src/generated` from the Rust wire types.

use std::fs;
use std::path::Path;

use anyhow::{Context, Result};
use ts_rs::TS;

use castellan_protocol::{
    Capability, ClientMessage, EntrySummary, Event, Hello, HostMessage, NewEntry, RpcError,
    RpcMethod, RpcRequest, RpcResponse, RpcResult, VaultStatus,
};

/// Where the generated TypeScript lives, relative to the repository root.
const GENERATED: &str = "packages/protocol/src/generated";

/// Export every wire type plus the barrel and the protocol version.
///
/// `export_all_to` writes one file per type *and* the files its definition
/// references, so the list below is the whole surface — adding a type to
/// `castellan-protocol` without adding it here fails the barrel check below,
/// not silently at the far end of a bundler.
pub(crate) fn run(root: &Path) -> Result<()> {
    let out = root.join(GENERATED);
    fs::create_dir_all(&out).context("creating the generated directory")?;

    // ts-rs 12 takes its output directory from the config, not from a method
    // argument: one config, then every type exports into it. `number` for
    // large ints because request ids are monotonically small and `bigint`
    // would force every caller through BigInt() for no gain; a type that
    // genuinely needs 64 bits (a YubiKey serial, a file size) says so by
    // being a String on the wire.
    let cfg = ts_rs::Config::new()
        .with_out_dir(&out)
        .with_large_int("number");

    Capability::export_all(&cfg)?;
    VaultStatus::export_all(&cfg)?;
    Hello::export_all(&cfg)?;
    EntrySummary::export_all(&cfg)?;
    NewEntry::export_all(&cfg)?;
    RpcMethod::export_all(&cfg)?;
    RpcRequest::export_all(&cfg)?;
    RpcError::export_all(&cfg)?;
    RpcResult::export_all(&cfg)?;
    RpcResponse::export_all(&cfg)?;
    Event::export_all(&cfg)?;
    ClientMessage::export_all(&cfg)?;
    HostMessage::export_all(&cfg)?;

    // ts-rs writes one file per type and no barrel; a hand-maintained barrel
    // is a second list to keep correct, so the generator writes it from the
    // same list of types it just exported.
    let barrel = [
        "Capability",
        "VaultStatus",
        "Hello",
        "EntrySummary",
        "NewEntry",
        "RpcMethod",
        "RpcRequest",
        "RpcError",
        "RpcResult",
        "RpcResponse",
        "Event",
        "ClientMessage",
        "HostMessage",
    ]
    .into_iter()
    .map(|ty| format!("export type {{ {ty} }} from \"./{ty}\";\n"))
    .chain(std::iter::once(
        "export { PROTOCOL_VERSION } from \"./version\";\n".to_string(),
    ))
    .collect::<String>();
    fs::write(out.join("index.ts"), barrel).context("writing the barrel")?;

    // The one non-type export: the protocol version, generated from the Rust
    // constant so the number a client sends in its hello is the number the
    // app actually compares against — a second hand-typed copy of a version
    // number is wrong after the first release nobody remembers to bump.
    fs::write(
        out.join("version.ts"),
        format!(
            "// Generated by castellan-xtask; do not edit.\nexport const PROTOCOL_VERSION: number = {};\n",
            castellan_protocol::PROTOCOL_VERSION
        ),
    )
    .context("writing version.ts")?;

    println!(
        "generated TypeScript bindings in {}",
        root.join(GENERATED).display()
    );
    Ok(())
}
