<script lang="ts">
import type { EntrySummary } from "@castellan/protocol";
import { onMount } from "svelte";

import EntryRow from "./EntryRow.svelte";
import LockedShield from "./LockedShield.svelte";

interface VaultHomeClient {
  ping(): Promise<void>;
  getEntries(origin: string): Promise<EntrySummary[]>;
  generatePassphrase(words: number, separator: string): Promise<string>;
}

interface Props {
  client: VaultHomeClient;
  mainClass: string;
  titleClass: string;
  sectionTitleClass: string;
  phraseClass: string;
  actionClass: string;
  emptyMessage: string;
  explainPassphrases?: boolean;
  origin?: string;
}

let {
  client,
  mainClass,
  titleClass,
  sectionTitleClass,
  phraseClass,
  actionClass,
  emptyMessage,
  explainPassphrases = false,
  origin = "https://github.com"
}: Props = $props();

let entries = $state<EntrySummary[]>([]);
let passphrase = $state("");
let error = $state("");

onMount(async () => {
  try {
    await client.ping();
    entries = await client.getEntries(origin);
  } catch (cause) {
    error = String(cause);
  }
});

async function roll(): Promise<void> {
  try {
    passphrase = await client.generatePassphrase(4, "-");
  } catch (cause) {
    error = String(cause);
  }
}

const host = $derived(origin.replace(/^https?:\/\//, "").split("/")[0]);
</script>

<main class={mainClass}>
  <header class="flex items-center gap-2">
    <LockedShield locked />
    <h1 class={titleClass}>Castellan</h1>
  </header>

  {#if error}
    <p class="error text-danger">{error}</p>
  {:else}
    <section>
      <h2 class={`c-section-title ${sectionTitleClass}`}>Entries for {host}</h2>
      {#if entries.length === 0}
        <p class="text-muted">{emptyMessage}</p>
      {:else}
        {#each entries as entry (entry.id)}
          <EntryRow {entry} />
        {/each}
      {/if}
    </section>

    <section>
      <h2 class={`c-section-title ${sectionTitleClass}`}>Passphrase</h2>
      {#if explainPassphrases}
        <p class="text-muted">
          Generated by the Rust core through the same RPC the extension speaks.
        </p>
      {/if}
      <code class={`phrase c-field ${phraseClass}`}>{passphrase || "—"}</code>
      <button class={`c-action ${actionClass}`} onclick={roll} type="button">Generate</button>
    </section>
  {/if}
</main>
