#!/bin/sh
# The airlock entry point. Hand-written on purpose: scripts/restore.sh is
# generated by `pixi-sandbox init` and must stay regenerable, so the two
# repository-specific repairs it cannot know about live here instead, around it.
#
# 1. The sandbox branch may not be in the clone. `restore.sh` runs `git archive`
#    against `origin/sandbox/<bundle>-<platform>`; a clone whose fetch refspec
#    covers only `main` and the branch being worked on does not have that ref and
#    restore dies with `not a valid object name`. One refspec-scoped fetch, and
#    only when no `origin/sandbox/*` ref exists yet, keeps a genuinely
#    disconnected airlock (where the ref is already local) from touching a remote.
#
# 2. Nothing points cargo at the restored vendor tree. pixi-sandbox wires the 489
#    vendored crates by writing `.cargo/config.toml`, finds the tracked one — the
#    file carrying the `TS_RS_EXPORT_DIR` codegen contract (AGENTS.md invariant 1)
#    — and correctly refuses to clobber it: `already exists — left alone`. The
#    crates land in `.pixi-sandbox/vendor/` with nothing referencing them, so the
#    next cargo call fails with `no matching package named proptest` and blames
#    offline mode for a config problem.
#
# Why the `[source]` block is not simply merged into the tracked config: source
# replacement pointing at a directory that does not exist is a hard cargo error,
# and the vendor tree exists only after a restore. CI and every networked
# contributor build from crates.io, so a tracked block would break them to fix
# the airlock. `cargo --config source.crates-io.replace-with=…` and
# `CARGO_SOURCE_*` environment variables do not work either — measured, not
# assumed: cargo honours source replacement only from a config *file* (the CLI
# key=value form and the env form both still fail to resolve `proptest`).
#
# What does work is a project-local `CARGO_HOME`: the one config layer cargo
# reads that is neither tracked nor global (`~/.cargo/config.toml` would impose
# crates.io replacement on every other project on the machine). The tracked
# `.cargo/config.toml` keeps precedence over it, so `[env] TS_RS_EXPORT_DIR`
# still reaches every cargo-spawned process — the two layers merge.
set -eu
ROOT=$(git rev-parse --show-toplevel)

if [ -z "$(git -C "$ROOT" for-each-ref --format=1 'refs/remotes/origin/sandbox/*')" ]; then
  echo "fetch sandbox branches (none in this clone)"
  git -C "$ROOT" fetch --no-tags origin 'refs/heads/sandbox/*:refs/remotes/origin/sandbox/*' ||
    echo "  fetch failed — continuing in case the branch is reachable locally" >&2
fi

"$ROOT/scripts/restore.sh" "$@"

VENDOR=$ROOT/.pixi-sandbox/vendor
ENV_SH=$ROOT/.pixi/sandbox-env.sh
CARGO_HOME_DIR=$ROOT/.pixi/cargo-home

echo "wire cargo to the vendored crates"
if [ ! -d "$VENDOR" ]; then
  echo "  no vendor tree (--no-vendor?) — cargo left on crates.io"
  exit 0
fi

mkdir -p "$CARGO_HOME_DIR"
# Absolute, because this layer is read from whatever directory cargo is invoked
# in, and a relative `directory` resolves against this file, not the project.
cat >"$CARGO_HOME_DIR/config.toml" <<EOF
# Written by scripts/airlock.sh after each restore; a machine artifact under the
# ignored .pixi/, never tracked. Reached only by a shell that sourced
# .pixi/sandbox-env.sh, which exports CARGO_HOME at this directory.
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "$VENDOR"
EOF

# sandbox-env.sh is regenerated by every restore, so the export is appended after
# restore ran, not assumed to have survived; the marker keeps repeated runs from
# stacking copies if a future pixi-sandbox preserves the file.
if ! grep -q 'airlock.sh: vendored cargo' "$ENV_SH" 2>/dev/null; then
  cat >>"$ENV_SH" <<EOF

# airlock.sh: vendored cargo. The tracked .cargo/config.toml must stay
# vendor-free (CI builds from crates.io), so the source replacement lives in a
# project-local CARGO_HOME instead — see scripts/airlock.sh for why this is the
# only layer that works.
export CARGO_HOME="$CARGO_HOME_DIR"
EOF
fi
echo "  CARGO_HOME -> $CARGO_HOME_DIR (exported by .pixi/sandbox-env.sh)"

# Prove it, here, rather than letting the first build discover it: resolution is
# the exact step that silently stayed broken after a successful restore.
echo "verify offline resolution"
if PATH="$ROOT/.pixi/envs/default/bin:$PATH" CARGO_HOME="$CARGO_HOME_DIR" \
  cargo metadata --offline --format-version 1 --manifest-path "$ROOT/Cargo.toml" >/dev/null; then
  echo "  OK — the workspace resolves against .pixi-sandbox/vendor"
else
  echo "  cargo still cannot resolve the workspace offline" >&2
  exit 1
fi

cat <<'EOF'
airlock ready
  source .pixi/sandbox-env.sh   # PATH, CARGO_NET_OFFLINE, CARGO_HOME
  cargo build --offline         # uses the restored vendor tree
EOF
