//! The WASM face of the shared logic.
//!
//! The extension runs this build in its service worker and content scripts;
//! the desktop and mobile apps link the *same functions* natively. That is
//! the "same scoped logic" promise made concrete: `parse_otpauth` here is
//! `castellan_otp::parse` there, one implementation, two targets, and the
//! TypeScript on top of it is generated by wasm-pack from the signatures.
//!
//! Only logic that must run without the app belongs here. Anything that
//! touches the vault, the socket, or the disk goes over the protocol to the
//! app process instead — the extension never holds a database, only answers.

use wasm_bindgen::prelude::*;

/// The protocol version of the shared logic this build was cut from.
///
/// Lets a packed extension answer `hello` checks without waking the app.
#[wasm_bindgen]
pub fn protocol_version() -> u32 {
    castellan_protocol::PROTOCOL_VERSION
}

/// A parsed `otpauth://` seed, as the extension sees it.
///
/// Mirrors [`castellan_otp::TotpConfig`] minus the raw secret bytes: the
/// extension gets the *shape* of the seed (issuer, account, digits, period)
/// for previews and validation, and asks the app for live codes through the
/// protocol. A secret that never reaches the extension is a secret that no
/// content script can read.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize)]
pub struct OtpAuthInfo {
    /// Issuer, from the URI path or `issuer` parameter.
    pub issuer: Option<String>,
    /// The account the seed belongs to.
    pub account: String,
    /// Code length in digits.
    pub digits: u32,
    /// Step in seconds.
    pub period: u32,
}

/// Parse an `otpauth://` URI for preview/validation, without the secret.
///
/// Plain Rust (no `wasm_bindgen` on the signature) so the apps link it
/// natively and the host-side tests exercise the real function; the
/// `#[wasm_bindgen]` wrapper below only adds the JS serialization.
pub fn otpauth_info(uri: &str) -> Result<OtpAuthInfo, castellan_otp::OtpError> {
    let config = castellan_otp::parse(uri)?;
    Ok(OtpAuthInfo {
        issuer: config.issuer,
        account: config.account,
        digits: config.digits,
        period: config.period,
    })
}

/// Errors surface as `JsError` so TypeScript `catch` blocks get a readable
/// message rather than a Rust panic.
#[wasm_bindgen]
pub fn parse_otpauth(uri: &str) -> Result<JsValue, JsError> {
    let info = otpauth_info(uri).map_err(JsError::from)?;
    serde_wasm_bindgen::to_value(&info).map_err(|e| JsError::new(&e.to_string()))
}

/// Whether an entry saved at `candidate` should be offered at `origin`.
///
/// The app uses the identical function when answering `get_entries`, so the
/// extension's local pre-filter and the app's authoritative answer can never
/// disagree about whether github.com matches accounts.github.com.
#[wasm_bindgen]
pub fn origin_matches(origin: &str, candidate: &str) -> bool {
    castellan_protocol::matching::origin_matches(origin, candidate)
}
