<script lang="ts">
import { CastellanClient } from "@castellan/core";
import type { EntrySummary } from "@castellan/protocol";
import { EntryRow, LockedShield } from "@castellan/ui";
import { onMount } from "svelte";
import { tauriTransport } from "$lib/transport";

const client = new CastellanClient(tauriTransport());

let entries = $state<EntrySummary[]>([]);
let passphrase = $state("");
let error = $state("");

onMount(async () => {
  try {
    await client.ping();
    entries = await client.getEntries("https://github.com");
  } catch (cause) {
    error = String(cause);
  }
});

async function roll(): Promise<void> {
  passphrase = await client.generatePassphrase(4, "-");
}
</script>

<!--
  Styling is UnoCSS from the shared config (uno.config.ts → the foundation
  in @castellan/utils/uno plus the looks in @castellan/ui/uno): the house
  looks are shortcuts (`c-section-title`, `c-field`, `c-action`), the
  desk-sized metrics are utilities right here —
  the mobile face renders the same markup at its own sizes. Bare classes
  like `error` are e2e hooks and carry no CSS.
-->
<main class="mx-auto flex max-w-640px flex-col gap-8 px-6 py-8">
  <header class="flex items-center gap-2">
    <LockedShield locked />
    <h1 class="m-0 text-[1.4rem]">Castellan</h1>
  </header>

  {#if error}
    <p class="error text-danger">{error}</p>
  {:else}
    <section>
      <h2 class="c-section-title text-[1rem]">Entries for github.com</h2>
      {#if entries.length === 0}
        <p class="text-muted">
          No entries yet — the vault core answers, and it is honestly empty.
        </p>
      {:else}
        {#each entries as entry (entry.id)}
          <EntryRow {entry} />
        {/each}
      {/if}
    </section>

    <section>
      <h2 class="c-section-title text-[1rem]">Passphrase</h2>
      <p class="text-muted">
        Generated by the Rust core through the same RPC the extension speaks.
      </p>
      <code class="phrase c-field mb-3 px-4 py-3 text-[1.05rem]">{passphrase || "—"}</code>
      <button class="c-action rounded-8px px-4 py-2" onclick={roll} type="button">Generate</button>
    </section>
  {/if}
</main>
